[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
JuliaSyntaxHighlighting = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"
TreeSitter = "f42328cb-ece0-4cf2-995f-9e7abb27d006"
tree_sitter_rust_jll = "b2197e8e-fe20-5781-846b-d7979e3cddf2"
